### ISSUE TITLE
Intensity Pro 4K not working with any non 4k resolution

### ISSUE THREAD

**Issue by Ernesto505** [elliotwoods/ofxBlackmagic2#10]
I am having an issue capturing anything other than 4k resolution out of the Intensity Pro 4K using the addon. It works correctly when the input is 3840x2160 but I am getting black frames when the image is anything different than that (1920X1080, 60hz e.g.).

I am on Windows 7 and I tested with openFrameworks 0.9 and 0.9.3 with the latest version of the addon.I use just a direct HDMI to HDMI cable so the cables shouldn't be the issue. 

The capture works correctly for the Blackmagic Media Express or the SDK sample apps. I checked the settings and they seem to be the same. 

Thanks,
Petros

**Comment by elliotwoods** [comment]
Hey Petros

Can you confirm that specifically:
* Your source is outputting 4K
* Media Express is working at 4K
* You're setting the same mode in ofxBlackMagic2 as you are in Media Express

I think you're suggesting that's what you already tested, but it would be
good to know for definite.

4k @30Hz capture works for me here (tested on windows 8,8.1,10 x64 with a
BlackMagic Cinema 4k connected via thunderbolt)

**Comment by Ernesto505** [comment]
Hi Elliot,

Thanks for your reply!

I think I was not quite clear. 4k Capture works fine for me too. I am getting black frames when I am trying to capture HD (1920x1080 60Hz). 

And to answer your questions but for HD:

1) My source is outputting HD 1920X1080 60 Hz.
2) Media express is working for HD 1920X1080 60 Hz.
3) I am setting the same mode in ofxBlackMagic2 as in Media Express 

I am on windows 7 x64 using an HDMI cable.

Thanks,
Petros

**Comment by elliotwoods** [comment]
Did you try changing the PSF setting in the BlackMagic control panel?

**Comment by elliotwoods** [comment]
As in, in your windows control panel (or wherever the settings are these
days :)

**Comment by elliotwoods** [comment]
Resolved?

Sent from Mail for Windows 10

**Comment by Ernesto505** [comment]
Unfortunately not. I played with the settings but I am still getting black frames when I try to capture 1920x1080 60hz.

**Comment by msf567** [comment]
I am having the same issues. I am outputting 2560 X 1440 from my GPU directly back into the capture card (for a purposeful feedback loop). Everything WAS working for a while, but now, all of a sudden I am receiving black frames. I have checked everything you have outlined above and I am receiving video no problem in Media Express. 

Anything else I should try?

**Comment by msf567** [comment]
I have also set everything to 1080p just for testing purposes.

Its very strange because it WAS working for a while, but now it is throwing [ error ] ofxBlackmagic::Input::startCapture: ofxBlackmagic::Input::startCapture: Failed to enable video input

**Comment by msf567** [comment]
I can also supply the entirety of my related code, if that helps.

I REALLY need to get this working, as my current project relies on this library.

**Comment by elliotwoods** [comment]
@msf567 : sorry but i don't have time to look through your code

to note : whenever i've tried local loopback it's never worked (no idea how it would even know that it is local loopback, but we did some extensive testing of this back in 2010 and local loopback always refused to work, even when the same stream worked on a second machine). maybe it's changed now (especially as you seem to have had it working previously. and it works fine in Media Express, right?)

@Ernesto505 
i'm a little baffled, but i presume it must be some kind of format problem
did you check the PSF settings?
did you try 59.97 (even though it's not the right one)

**Comment by mattsonic** [comment]
I had this same problem and figured out a fix. Pull request here: https://github.com/elliotwoods/ofxBlackmagic2/pull/13

**Comment by elliotwoods** [comment]
Thanks @mattsonic !
I've pulled your changes
Will close this issue for now (can't test myself) and reopen if still isn't working for people
